var UserConstants = {
	LOGIN: "LOGIN",
	ERROR: "ERROR",
	LOGOUT: "LOGOUT",
	USERS_RECEIVED: "USERS_RECEIVED",
	USER_RECEIVED: "USER_RECEIVED",
	USER_REMOVED: "USER_REMOVED"
};

module.exports = UserConstants;
